# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ico-app-ac

test:
  <<: *default
  database: ico-app-ac_test

production:
  <<: *default
  database: ico-app-ac
  username: ico-app-ac
  password: <%= ENV['ICO-APP-AC_DATABASE_PASSWORD'] %>
